name: Build for Release

on:
  [push]

env:
  pkg-name: 'nocode-app'
  pkg-version: '1.0'
  #the short version is useful for the linux build, which truncates the 1.0 into 1
  pkg-version-short: '1'

jobs:

  linux-deb-installer-creation:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '15'
        java-package: jdk
        architecture: x64

    - name: View artifacts
      run: ls

    - name: run jlink
      run: "jlink --no-header-files --no-man-pages --module-path linux/core --add-modules net.clementlevallois.nocodeapp.core --bind-services --output image --compress=1"

    - name: run jpackage
      run: "jpackage --type deb -n ${{ env.pkg-name }} --module-path linux/core --runtime-image image -m net.clementlevallois.nocodeapp.core/net.clementlevallois.nocodeappcore.controller.RealMain"

    - name: View artifacts
      run: ls

    - name: upload deb installer to temp github action working folder
      uses: actions/upload-artifact@v2
      with:
        name: deb
        #ATTENTION HERE LINUX FOLLOWS THIS WEIRD PATTERN OF NAMING, WHICH IS REPEATED BELOW
        path: "${{ env.pkg-name }}_${{ env.pkg-version }}-${{ env.pkg-version-short }}_amd64.deb"
        if-no-files-found: warn
    - name: create release for deb installer
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.pkg-name }}-linux-${{ env.pkg-version }}.0.1
        release_name: Release ${{ env.pkg-name }}--linux-${{ env.pkg-version }}.0.1
        body: |
          Changes in this Release
          - alpha version
          - not stable
        draft: false
        prerelease: false
          
    - name: Upload deb package to release page
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: "./${{ env.pkg-name }}_${{ env.pkg-version }}-${{ env.pkg-version-short }}_amd64.deb"
        asset_name: ${{ env.pkg-name }}_${{ env.pkg-version }}-${{ env.pkg-version-short }}_amd64.deb
        asset_content_type: application/vnd.debian.binary-package